// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYT8_ZhdsdRFeLxas9prrcuDhqgpUJOU0',
    appId: '1:270067789991:web:fe888c6ceb17d43d192b82',
    messagingSenderId: '270067789991',
    projectId: 'topic-trail',
    authDomain: 'topic-trail.firebaseapp.com',
    storageBucket: 'topic-trail.appspot.com',
    measurementId: 'G-9BE9VQ2PL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGgq9JoQbucvw0EtTxBX7xFb0cBj0Y2VU',
    appId: '1:270067789991:android:36d133d4a3a113e4192b82',
    messagingSenderId: '270067789991',
    projectId: 'topic-trail',
    storageBucket: 'topic-trail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0WRaFMwV9LkY4lr81bPoEkuRKhNj3Hs',
    appId: '1:270067789991:ios:e95f0aab6bb29540192b82',
    messagingSenderId: '270067789991',
    projectId: 'topic-trail',
    storageBucket: 'topic-trail.appspot.com',
    iosClientId: '270067789991-7qhpqoq56ps28sp2kshrvs9ks3qiiads.apps.googleusercontent.com',
    iosBundleId: 'com.example.topicTrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0WRaFMwV9LkY4lr81bPoEkuRKhNj3Hs',
    appId: '1:270067789991:ios:e95f0aab6bb29540192b82',
    messagingSenderId: '270067789991',
    projectId: 'topic-trail',
    storageBucket: 'topic-trail.appspot.com',
    iosClientId: '270067789991-7qhpqoq56ps28sp2kshrvs9ks3qiiads.apps.googleusercontent.com',
    iosBundleId: 'com.example.topicTrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYT8_ZhdsdRFeLxas9prrcuDhqgpUJOU0',
    appId: '1:270067789991:web:6f53669201ed68cb192b82',
    messagingSenderId: '270067789991',
    projectId: 'topic-trail',
    authDomain: 'topic-trail.firebaseapp.com',
    storageBucket: 'topic-trail.appspot.com',
    measurementId: 'G-9V64CJSHP6',
  );
}
